name: Meter Parser
version: dev
slug: meter-parser
description: Read meter needles and numbers from a camera snapshot.
url: https://github.com/junalmeida/ha-meterparser-addon
init: false
services:
  - "mqtt:need"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  cameras:
    - snapshot_url: http://192.168.1.10/cam.mjpeg
      name: Water Meter
      interval: 5 # minutes
schema:
  cameras:
    - snapshot_url: str
      name: str
      interval: int(1,3600)
